### PR TITLE
Fmod fixes

### PR DESCRIPTION
**Pull request by Schroedingers-Cat**
* **Please check if the pull request fulfills these requirements**
- [ ] Tests are not feasible for this fix
- [ ] Docs will be updated after these fixes merged
- [x] CHANGELOG.md has been updated to describe this change and other changes that went under the radar during the recent repo migration

* **What kind of change does this pull request introduce?**

- [x] Bug Fix
- [ ] Feature
- [x] Something else

* **What is the current behavior?** (You can also link to an open issue here)
The FMOD playback component is broken because of a recent change in the RunLine signature of the ViewBase class. 

* **What is the new behavior (if this is a feature change)?**
The FMOD playback component has been changed to correctly implement the abstract RunLine method and also calls the onDialogueDeliveryComplete() callback after playback finished.

Additionally, this PR includes ready to use asmdefs for FMOD in a unitypackage to make the integration process faster and easier. YarnSpinner's asmdef also references the FMOD asmdef.

* **Does this pull request introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No breaking changes.

* **Other information**:
The included reference to FMOD in YarnSpinner's asmdef has been tested in Unity 2018 and 2019 with and without the FMOD library present in the project and the project worked in all situations.

### CODE REVIEW

**Comment by desplesda** [comment]
What does Samples~/Voice Over/Audio/FmodAssemblyDefinitions.unitypackage contain?

**Comment by Schroedingers-Cat** [comment]
> What does Samples~/Voice Over/Audio/FmodAssemblyDefinitions.unitypackage contain?

It contains two assembly definitions necessary for yarn to be able to reference fmod.

**Comment by desplesda** [comment]
Ok, cool - if using this sample requires an additional step to use (beyond "open the scene"), what's the best way to explain it to the user? In-scene text?

**Comment by Schroedingers-Cat** [comment]
I did this PR in preparation for adding VO to the docs repo. Would it this suffice or should I also add a separate readme to this directory?

**Comment by desplesda** [comment]
I feel like adding in a description for a critical step in the code makes the most sense - we can't guarantee that a user will think to read the docs, and will just think that FMOD is broken. I'm thinking a text file like "FMOD-Instructions.txt", containing instructions.

Another thing to note is that .unitypackage files extract to specific locations, but if a user has installed Yarn Spinner via the package manager, the location of any sample content includes the version number, so the .asmdef will likely be in the wrong place. A solution might be to store the .asmdef in a zip file, which can be extracted in-place?

**Comment by desplesda** [comment]
We removed FMOD support from v2.1.0, so this PR no longer applies. As a result, I'll close this PR here. (Thanks again for doing the work! Sorry that it no longer fits!!)

**Pull request closed without merging**
