### PR TITLE
InMemoryVariableStorage redesign + serialization + example save/load functions

### PR DESCRIPTION
**Pull request by radiatoryang**
* **Please check if the pull request fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated to describe this change

To update the documentation on [yarnspinner.dev](https://yarnspinner.dev), please visit the [documentation repository](https://github.com/YarnSpinnerTool/Docs).

* **What kind of change does this pull request introduce?**

- [x] Bug Fix
- [x] Feature
- [ ] Something else

* **What is the current behavior?** (You can also link to an open issue here)

DefaultVariables (initial variable value override via Unity inspector) was broken for v2.0

Since Yarn.Value is now internal only, it might be difficult for users to understand how to serialize variables stored as System.Object

* **What is the new behavior (if this is a feature change)?**

~~DefaultVariables behavior restored, along with configurable "ResetToDefaultOnStart" bool (default: true) to help surface what DefaultVariables actually is -- which imo is useful for playtesting?~~ seems DefaultVariables functionality has been basically moved to the YarnProgram asset inspector, and it's unclear how this interacts with v2.0 variable declarations? so maybe it really should be removed from InMemoryVariableStorage now?

Variables can now be serialized via JsonUtility, with example functions for saving to PlayerPrefs or writing to a file

* **Does this pull request introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

While we're talking about types, should there be a Yarn.Type.Float and a Yarn.Type.Int, vs the existing Yarn.Type.Number?

* **Other information**:

Draft status for now, still have to test with an actual Yarn test script that sets / gets variables

In the future, if https://github.com/YarnSpinnerTool/YarnSpinner/pull/242 get finished, it'd be cool to pull the Save/Load functions out into a separate SaveManager.cs script that shows how to save and load both VM state + Variable Storage at the same time

### CODE REVIEW

**Comment by radiatoryang** [comment]
ok this has turned into a soft redesign of InMemoryVariableStorage...

- DefaultVariables functionality has been removed to push users to use YarnProgram inspector instead
- added a debug variable list display in inspector, so you don't have to create and assign a Text debug just to see your variables, should improve workflow for a lot of people

image

**Comment by desplesda** [comment]
This looks really good! This is a great approach, and I really like the new inspector debug view.

Before I merge this, would you be able to add some unit tests that exercise the following methods:

* `SetValue`
* `TryGetValue`
* `SaveToPlayerPrefs`
* `SaveToFile`
* `LoadFromPlayerPrefs`
* `LoadFromFile`

**Comment by radiatoryang** [comment]
tests added under Tests/Runtime/VariableStorageTests

**Comment by desplesda** [comment]
Excellent! Thank you!

(Note: When I imported this into Unity 2018, I had to do a little bit of reference fixup (the local file ID appeared to be different between your version and mine.) Once fixed, the new unit tests passed.)

**Pull request merged**
