### PR TITLE
Feature/chat sample

### PR DESCRIPTION
**Pull request by radiatoryang**
* **Please check if the pull request fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated to describe this change

To update the documentation on [yarnspinner.dev](https://yarnspinner.dev), please visit the [documentation repository](https://github.com/YarnSpinnerTool/Docs).

* **What kind of change does this pull request introduce?**

- [ ] Bug Fix
- [x] Feature
- [ ] Something else

* **What is the current behavior?** (You can also link to an open issue here)

N/A

* **What is the new behavior (if this is a feature change)?**

Adds a new sample project for a phone chat text messaging app, demonstrates how you can hook in a simple helper MonoBehaviour script (PhoneChatDialogueHelper.cs) to clone new message bubbles for each line of dialogue... also demonstrates a tricky thing in Unity UI, how to make a dynamically resizing text bubble.

* **Does this pull request introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Not that I know of!

* **Other information**:

Is there a good place in the documentation repo where we should describe the samples, and maybe include a sample image or GIF?

### CODE REVIEW

**Comment by desplesda** [comment]
This looks incredible!

I noticed that the sample uses commands to switch between senders, rather than character names. Would it be better with character names, or is the use of commands a deliberate choice to show how to use them in this context?

**Comment by radiatoryang** [comment]
I thought it'd be helpful and instructive to show a different way, yeah.

**Comment by desplesda** [comment]
Ok, cool!

**Comment by desplesda** [comment]
This looks really good! Happy to merge into `develop`. I might also add some smaller features, like the automatic `<<wait>>` based on line length, too.

**Pull request merged**
